# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'BasicRegressionAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift'

  target 'BasicRegressionAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BasicRegressionAIUITests' do
    # Pods for testing
  end

end
